local import = require(game.ReplicatedStorage.Shared.Import)

local loadOrder = {
	"Shared/PlayerData",
	"Shared/Systems/Sounds",
	"../Systems/Animations",
	"../Systems/Commands",
	--"Shared/Systems/Chat",
	"Shared/Systems/Ragdoll",
	"Shared/Utils/Date",
	"../Systems/ClickDetectors",
	"../Systems/Particles",
	"../Systems/Tools",
	"../Systems/Equipment",
	"../Systems/Damage",
	"../Systems/Explosions",
	"../Systems/Projectiles",
	"../Systems/Hitboxes",
	"../Systems/Knockback",
	"../Systems/Fire",
	"../Systems/Players",
	"../Systems/GameLoop",
	"../Systems/Construction",
	"../Systems/Lava",
	"../Systems/Balls",
	"../Systems/Boomerangs",
	"../Systems/RoundReturn",
	"../Systems/DailyRewards",
	"../Systems/Tasks",
	"../Systems/ShopManager",
	"../Systems/Turrets",
	"../Systems/Grapple",
	"../Systems/DailyChests",
	"../Systems/SafeZones",
	"../Systems/Purchases",
	"../Systems/Sprays",
	"../Systems/Trampolines",
	"../Systems/AlphaReward",
	"../Systems/LastTeamTracker",
	"../Systems/GamemodeInformation",
	"../Systems/SpawnCapturing",
	"../Systems/Invisibility",
	"../Systems/Afk",
	"../Systems/Codes",
	"../Systems/PartHealth",
	"../Systems/StickerDataReplicator",
	"../Systems/Outfits",
	"../Systems/Tips",
}
--:epictroll: :epictroll: :epictroll: :epictroll: :epictroll:
for _, path in ipairs(loadOrder) do
	local system = import(path)
	system:start()
end
